In [21]:
# student performance analysis using python
# PCA- to find most contributing factor and recude the size to smaller size to analyze the data
# define problem, import libraries, load, explore, clean, analyize, visualize, conclusion

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jealousleopard/goodreadsbooks")

print("Path to dataset files:", path)

C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\DELL\.cache\kagglehub\datasets\jealousleopard\goodreadsbooks\2.archive...

100%|██████████| 622k/622k [00:01<00:00, 483kB/s]

Extracting files...
Path to dataset files: C:\Users\DELL\.cache\kagglehub\datasets\jealousleopard\goodreadsbooks\versions\2

In [ ]:
# Using goodreads books, kaggle dataset

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
# Load the dataset as dataframe
df = pd.read_csv(
    "books.csv",
    engine="python",
    on_bad_lines="skip",
    encoding="utf-8"
)

df.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [ ]:
print("Shape: ",df.shape) #rows,columns
print(df.columns) # column name
df.dtypes  #data types and no.of columns for that
df.sample(5)  #any 5 rows

Shape:  (11119, 12)
Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='str')

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
952,3145,Drina Ballerina,Jean Estoril,4.16,0750005947,9780750005944,eng,188,8,1,1/17/1991,Hodder
3267,11991,The Fall,Albert Camus/Justin O'Brien,4.04,0679720227,9780679720225,eng,147,53697,1772,5/7/1991,Vintage
237,664,The Fountainhead,Ayn Rand,3.87,0452286751,9780452286757,en-US,752,1886,229,4/26/2005,Dutton
7671,29561,The Truth Will Set You Free: Overcoming Emotio...,Alice Miller/Andrew Edwin Jenkins,4.06,0465045855,9780465045853,eng,224,501,32,12/10/2002,Basic Books
8461,32520,Sonnets,William Shakespeare/Stephen Booth,4.25,0300085060,9780300085068,eng,583,104,6,7/11/2000,Yale University Press

In [11]:
df.tail() #last 5 rows

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
11114,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,9781560254416,eng,512,156,20,12/21/2004,Da Capo Press
11115,45633,You Bright and Risen Angels,William T. Vollmann,4.08,0140110879,9780140110876,eng,635,783,56,12/1/1988,Penguin Books
11116,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,0140131965,9780140131963,eng,415,820,95,8/1/1993,Penguin Books
11117,45639,Poor People,William T. Vollmann,3.72,0060878827,9780060878825,eng,434,769,139,2/27/2007,Ecco
11118,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,9788497646987,spa,272,113,12,5/28/2006,Edimat Libros

In [10]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 11119 entries, 0 to 11118
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11119 non-null  int64
 1   title               11119 non-null  str
 2   authors             11119 non-null  str
 3   average_rating      11119 non-null  float64
 4   isbn                11119 non-null  str
 5   isbn13              11119 non-null  int64
 6   language_code       11119 non-null  str
 7     num_pages         11119 non-null  int64
 8   ratings_count       11119 non-null  int64
 9   text_reviews_count  11119 non-null  int64
 10  publication_date    11119 non-null  str
 11  publisher           11119 non-null  str
dtypes: float64(1), int64(5), str(6)
memory usage: 1.0 MB

,bookID,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,11119.000000,11119.000000,1.111900e+04,11119.000000,1.111900e+04,11119.000000
mean,21308.966184,3.934135,9.759873e+12,336.439788,1.794832e+04,542.167371
std,13093.071002,0.350384,4.430554e+11,241.177969,1.125190e+05,2577.069549
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10277.500000,3.770000,9.780345e+12,192.000000,1.040000e+02,9.000000
50%,20287.000000,3.960000,9.780586e+12,299.000000,7.450000e+02,47.000000
75%,32103.500000,4.135000,9.780873e+12,416.000000,5.000500e+03,238.000000
max,45641.000000,5.000000,9.790008e+12,6576.000000,4.597666e+06,94265.000000

In [12]:
df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [15]:
print("Duplicate rows: ",df.duplicated().sum())

Duplicate rows:  0

In [16]:
df.dtypes

bookID                  int64
title                     str
authors                   str
average_rating        float64
isbn                      str
isbn13                  int64
language_code             str
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date          str
publisher                 str
dtype: object

In [17]:
df['authors'].unique()

<StringArray>
[                                 'J.K. Rowling/Mary GrandPré',
                                                'J.K. Rowling',
                                      'W. Frederick Zimmerman',
                                               'Douglas Adams',
                                   'Douglas Adams/Stephen Fry',
                                                 'Bill Bryson',
                                              'J.R.R. Tolkien',
                                    'J.R.R. Tolkien/Alan  Lee',
               'Chris   Smith/Christopher  Lee/Richard Taylor',
                                                 'Jude Fisher',
 ...
                                            'Alexander Hunter',
                                    'Roald Dahl/Horacio Elena',
                                       'David Wood/Roald Dahl',
                     'Dave Crane/Eric Pascarello/Darren James',
                                                'Rosa Montero',
                                          'Mario Vargas Llosa',
 'C.S. Lewis/Margarita E. Valdes/Gemma Gallart/Pauline Baynes',
                                'C.S. Lewis/Ana Falcão Bastos',
                 'C.S. Lewis/Pauline Baynes/Ana Falcão Bastos',
      'William T. Vollmann/Larry McCaffery/Michael Hemmingson']
Length: 6635, dtype: str

In [18]:
df['language_code'].unique()

<StringArray>
[  'eng', 'en-US',   'fre',   'spa', 'en-GB',   'mul',   'grc',   'enm',
 'en-CA',   'ger',   'jpn',   'ara',    'nl',   'zho',   'lat',   'por',
   'srp',   'ita',   'rus',   'msa',   'glg',   'wel',   'swe',   'nor',
   'tur',   'gla',   'ale']
Length: 27, dtype: str

In [26]:
# remove extra spaces
df['authors']=df['authors'].str.strip()
df['publisher']=df['publisher'].str.strip()
df["title"] = df["title"].str.strip()

In [20]:
df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [22]:
df["language_code"].value_counts()

language_code
eng      8906
en-US    1406
spa       218
en-GB     214
fre       144
ger        99
jpn        46
mul        19
zho        14
grc        11
por        10
en-CA       7
ita         5
enm         3
lat         3
rus         2
swe         2
ara         1
nl          1
srp         1
msa         1
glg         1
wel         1
nor         1
tur         1
gla         1
ale         1
Name: count, dtype: int64

In [23]:
df['language_code']=df['language_code'].replace({
    "en-CA":"eng",
    "en-US": "eng",
    "en-GB": "eng"
})

In [25]:
df['language_code'].value_counts()

language_code
eng    10533
spa      218
fre      144
ger       99
jpn       46
mul       19
zho       14
grc       11
por       10
ita        5
enm        3
lat        3
rus        2
swe        2
ara        1
nl         1
srp        1
msa        1
glg        1
wel        1
nor        1
tur        1
gla        1
ale        1
Name: count, dtype: int64

In [27]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 11119 entries, 0 to 11118
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11119 non-null  int64
 1   title               11119 non-null  str
 2   authors             11119 non-null  str
 3   average_rating      11119 non-null  float64
 4   isbn                11119 non-null  str
 5   isbn13              11119 non-null  int64
 6   language_code       11119 non-null  str
 7     num_pages         11119 non-null  int64
 8   ratings_count       11119 non-null  int64
 9   text_reviews_count  11119 non-null  int64
 10  publication_date    11119 non-null  str
 11  publisher           11119 non-null  str
dtypes: float64(1), int64(5), str(6)
memory usage: 1.0 MB

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic