In [11]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [12]:
#read dataset
df=pd.read_csv(r"../data/Titanic-Dataset.csv")
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
#fill age with mean
age_imputer=SimpleImputer(strategy='mean') #fills null value with the strategy
#use simple imputer when no. of null values is less, if more just remove
df['Age']=age_imputer.fit_transform(df[['Age']])

In [15]:
#fill embarked with most frequent value
#embarked is which port people are getting on ship, it is CATEGORICAL DATA
#so fill with the mode i.e. most frequent
embarked_imputer=SimpleImputer(strategy='most_frequent')
df['Embarked']=embarked_imputer.fit_transform(df[['Embarked']]).ravel()
#ravel to convert 2d to 1d

In [16]:
df.shape

(891, 12)

In [17]:
#drop cabin #inplace=True means doing in dataset also
df.drop('Cabin',axis=1,inplace=True)

In [18]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [19]:
#feature selection: remove unnecessary columns
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [20]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [21]:
#feature encoding: label encoder
#sex: male, female, 0 and 1
le=LabelEncoder()
df['Sex']= le.fit_transform(df['Sex'])

In [22]:
print(le.classes_)

['female' 'male']

In [ ]:
#feature encoding: ONE-HOT ENCODING, so no numerical priority to anyone
#different values to different values everytime
#only model can understad
#no bias to any particular category
#embarked as variety of category
#get_dummies
df=pd.get_dummies(df,columns=['Embarked'],dtype=int)

In [25]:
df.head()

   Survived  Pclass  Sex   Age  ...     Fare  Embarked_C  Embarked_Q  Embarked_S
0         0       3    1  22.0  ...   7.2500           0           0           1
1         1       1    0  38.0  ...  71.2833           1           0           0
2         1       3    0  26.0  ...   7.9250           0           0           1
3         1       1    0  35.0  ...  53.1000           0           0           1
4         0       3    1  35.0  ...   8.0500           0           0           1

[5 rows x 10 columns]

In [26]:
#separate features and target
X=df.drop('Survived',axis=1)
y=df['Survived']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
#feature scaling
scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
#check output from standard scaler thing
print(X_train[:5])

[[-1.61413602  0.7243102   1.22920747 -0.47072241 -0.47934164 -0.07868358
  -0.46146201 -0.30335547  0.59248936]
 [-0.40055118  0.7243102  -0.50350514 -0.47072241 -0.47934164 -0.37714494
  -0.46146201 -0.30335547  0.59248936]
 [ 0.81303367  0.7243102   0.18957991 -0.47072241 -0.47934164 -0.47486697
  -0.46146201 -0.30335547  0.59248936]
 [ 0.81303367  0.7243102  -0.27247679  0.37992316 -0.47934164 -0.47623026
  -0.46146201 -0.30335547  0.59248936]
 [ 0.81303367 -1.38062393 -1.81266577  2.93185988  2.04874166 -0.02524937
  -0.46146201 -0.30335547  0.59248936]]

Pre-processing done to make sure data is efficient to increase accuracy and efficieny of our model

In [29]:
#train model
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=5)

model.fit(X_train, y_train)

KNeighborsClassifier()

In [30]:
#predict
y_pred=model.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.7988826815642458

In [32]:
#cross val score
from sklearn.model_selection import cross_val_score

In [ ]:
scores=cross_val_score(model, X_train, y_train, cv=5) #we give value on our own
print(scores)

[0.82517483 0.78321678 0.80985915 0.76056338 0.82394366]

In [34]:
print("Average Accuracy:",scores.mean())

Average Accuracy: 0.8005515611149413

In [35]:
#grid search cv
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [36]:
params={
    "n_neighbors":[3,5,7,9,11],
    "weights":['uniform','distance'],
    "metric":['euclidean','manhattan']
}

In [37]:
#grid search object
grid = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=params,
    cv=5,
    scoring='accuracy'
)

In [38]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [39]:
print("Best Parameters:")
print(grid.best_params_)

Best Parameters:
{'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'uniform'}

In [ ]:
#best cv score
print("Best Cross Validation Accuracy:")
print(grid.best_score_) #avg best accuracy

Best Cross Validation Accuracy:
0.8103910174332709

In [41]:
#train best model
best_model=grid.best_estimator_

In [42]:
y_pred=best_model.predict(X_test)
print("Accuracy after grid search:")
print(accuracy_score(y_test,y_pred))

Accuracy after grid search:
0.7877094972067039

In [43]:
#randomized search cv
from sklearn.model_selection import RandomizedSearchCV

In [44]:
#object
random=RandomizedSearchCV(
    estimator=KNeighborsClassifier(),
    param_distributions=params,
    n_iter=5,
    cv=5,
    scoring='accuracy',
    random_state=42
)

In [45]:
random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=5,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': [3, 5, 7, 9, 11],
                                        'weights': ['uniform', 'distance']},
                   random_state=42, scoring='accuracy')

In [46]:
print("Best Parameters:")
print(random.best_params_)

Best Parameters:
{'weights': 'uniform', 'n_neighbors': 11, 'metric': 'euclidean'}

In [47]:
print("Best CV Accuracy:")
print(random.best_params_)

Best CV Accuracy:
{'weights': 'uniform', 'n_neighbors': 11, 'metric': 'euclidean'}

In [ ]:
#Best random model
best_random=random.best_estimator_
y_pred=best_random.predict(X_test)
print("Accuracy After Random Search:")
print(accuracy_score(y_test,y_pred))

Accuracy After Random Search:
0.7877094972067039

In [50]:
print("Before Tuning:",accuracy_score(y_test,model.predict(X_test)))
print("Grid Search:",accuracy_score(y_test,best_model.predict(X_test)))
print("Random Search:",accuracy_score(y_test,best_random.predict(X_test)))

Before Tuning: 0.7988826815642458
Grid Search: 0.7877094972067039
Random Search: 0.7877094972067039